<a href="https://colab.research.google.com/github/KeshUdana/MLTutorials/blob/main/Tut02ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [37]:
import pandas as pd

data_frame=pd.read_csv("/content/drive/MyDrive/Mall_Customers.csv")
list(data_frame.columns)
data_frame.info()
data_frame.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      200 non-null    int64
 1   Sex                     200 non-null    int64
 2   Age                     197 non-null    float64
 3   Salary                  198 non-null    float64
 4   Spending Score (1-100)  199 non-null    float64
 5   New-Column              200 non-null    int64
 6   Customer_Satisfaction   200 non-null    object
dtypes: float64(3), int64(3), object(1)
memory usage: 11.1+ KB

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column,Customer_Satisfaction
0,1,0,19.0,15.0,NaN,1,Unsatisfied
1,2,0,NaN,15.0,81.0,1,Satisfied
2,3,1,20.0,16.0,6.0,1,Unsatisfied
3,4,1,23.0,NaN,77.0,1,Satisfied
4,5,1,NaN,NaN,40.0,1,Unsatisfied
5,6,1,22.0,17.0,76.0,1,Satisfied
6,7,1,NaN,18.0,6.0,1,Unsatisfied
7,8,1,23.0,18.0,94.0,1,Satisfied
8,9,0,64.0,19.0,3.0,1,Unsatisfied
9,10,1,30.0,19.0,72.0,1,Satisfied

In [38]:
data_frame.describe()

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column
count,200.000000,200.000000,197.000000,198.000000,199.000000,200.0
mean,100.500000,0.560000,39.000000,61.005051,50.256281,1.0
std,57.879185,0.497633,14.002915,26.017857,25.876350,0.0
min,1.000000,0.000000,18.000000,15.000000,1.000000,1.0
25%,50.750000,0.000000,29.000000,42.250000,34.500000,1.0
50%,100.500000,1.000000,36.000000,62.000000,50.000000,1.0
75%,150.250000,1.000000,49.000000,78.000000,73.000000,1.0
max,200.000000,1.000000,70.000000,137.000000,99.000000,1.0

In [39]:
data_frame.describe(include='object')

       Customer_Satisfaction
count                    200
unique                     2
top              Unsatisfied
freq                     146

In [40]:
print("Number of null values in each column")
data_frame.isnull().sum()

Number of null values in each column

ID                        0
Sex                       0
Age                       3
Salary                    2
Spending Score (1-100)    1
New-Column                0
Customer_Satisfaction     0
dtype: int64

In [41]:
data_frame.isna().sum()/len(data_frame)*100

ID                        0.0
Sex                       0.0
Age                       1.5
Salary                    1.0
Spending Score (1-100)    0.5
New-Column                0.0
Customer_Satisfaction     0.0
dtype: float64

In [42]:
data_frame.shape

(200, 7)

In [43]:
data_frame.drop(data_frame.index[3],inplace=True);
data_frame.head()

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column,Customer_Satisfaction
0,1,0,19.0,15.0,NaN,1,Unsatisfied
1,2,0,NaN,15.0,81.0,1,Satisfied
2,3,1,20.0,16.0,6.0,1,Unsatisfied
4,5,1,NaN,NaN,40.0,1,Unsatisfied
5,6,1,22.0,17.0,76.0,1,Satisfied

In [44]:
import pandas as pd

data_frame = pd.read_csv("/content/drive/MyDrive/Mall_Customers.csv")
data_frame.rename({'CustomerID': "ID", 'Gender': "Sex", 'Annual Income (k$)': "Salary"}, axis=1, inplace=True)
data_frame.head()

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column,Customer_Satisfaction
0,1,0,19.0,15.0,NaN,1,Unsatisfied
1,2,0,NaN,15.0,81.0,1,Satisfied
2,3,1,20.0,16.0,6.0,1,Unsatisfied
3,4,1,23.0,NaN,77.0,1,Satisfied
4,5,1,NaN,NaN,40.0,1,Unsatisfied

In [45]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
label_encoder = preprocessing.LabelEncoder()
data_frame['Sex']= label_encoder.fit_transform(data_frame['Sex'])
data_frame.head(100)

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column,Customer_Satisfaction
0,1,0,19.0,15.0,NaN,1,Unsatisfied
1,2,0,NaN,15.0,81.0,1,Satisfied
2,3,1,20.0,16.0,6.0,1,Unsatisfied
3,4,1,23.0,NaN,77.0,1,Satisfied
4,5,1,NaN,NaN,40.0,1,Unsatisfied
...,...,...,...,...,...,...,...
95,96,0,24.0,60.0,52.0,1,Unsatisfied
96,97,1,47.0,60.0,47.0,1,Unsatisfied
97,98,1,27.0,60.0,50.0,1,Unsatisfied
98,99,0,48.0,61.0,42.0,1,Unsatisfied
99,100,0,20.0,61.0,49.0,1,Unsatisfied

In [46]:
data_frame.rename({' Spending Score (1-100)':"Spending_Score"}, axis=1,
inplace=True)
data_frame.head(20)

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column,Customer_Satisfaction
0,1,0,19.0,15.0,NaN,1,Unsatisfied
1,2,0,NaN,15.0,81.0,1,Satisfied
2,3,1,20.0,16.0,6.0,1,Unsatisfied
3,4,1,23.0,NaN,77.0,1,Satisfied
4,5,1,NaN,NaN,40.0,1,Unsatisfied
5,6,1,22.0,17.0,76.0,1,Satisfied
6,7,1,NaN,18.0,6.0,1,Unsatisfied
7,8,1,23.0,18.0,94.0,1,Satisfied
8,9,0,64.0,19.0,3.0,1,Unsatisfied
9,10,1,30.0,19.0,72.0,1,Satisfied
10,11,0,67.0,19.0,14.0,1,Unsatisfied
11,12,1,35.0,19.0,99.0,1,Satisfied
12,13,1,58.0,20.0,15.0,1,Unsatisfied
13,14,1,24.0,20.0,77.0,1,Satisfied
14,15,0,37.0,20.0,13.0,1,Unsatisfied
15,16,0,22.0,20.0,79.0,1,Satisfied
16,17,1,35.0,21.0,35.0,1,Unsatisfied
17,18,0,20.0,21.0,66.0,1,Unsatisfied
18,19,0,52.0,23.0,29.0,1,Unsatisfied
19,20,1,35.0,23.0,98.0,1,Satisfied

In [47]:
def satisfaction(value):
 if value > 70:
  return "Satisfied"
 else:
  return "Unsatisfied"

In [48]:
print(data_frame.columns)

Index(['ID', 'Sex', 'Age', 'Salary', 'Spending Score (1-100)', 'New-Column',
       'Customer_Satisfaction'],
      dtype='object')

In [49]:
data_frame['Spending Score (1-100)'].apply(satisfaction)

0      Unsatisfied
1        Satisfied
2      Unsatisfied
3        Satisfied
4      Unsatisfied
          ...
195      Satisfied
196    Unsatisfied
197      Satisfied
198    Unsatisfied
199      Satisfied
Name: Spending Score (1-100), Length: 200, dtype: object

In [50]:
data_frame['Customer_Satisfaction'] = data_frame['Spending Score (1-100)'].apply(satisfaction)
data_frame.head(20)

,ID,Sex,Age,Salary,Spending Score (1-100),New-Column,Customer_Satisfaction
0,1,0,19.0,15.0,NaN,1,Unsatisfied
1,2,0,NaN,15.0,81.0,1,Satisfied
2,3,1,20.0,16.0,6.0,1,Unsatisfied
3,4,1,23.0,NaN,77.0,1,Satisfied
4,5,1,NaN,NaN,40.0,1,Unsatisfied
5,6,1,22.0,17.0,76.0,1,Satisfied
6,7,1,NaN,18.0,6.0,1,Unsatisfied
7,8,1,23.0,18.0,94.0,1,Satisfied
8,9,0,64.0,19.0,3.0,1,Unsatisfied
9,10,1,30.0,19.0,72.0,1,Satisfied
10,11,0,67.0,19.0,14.0,1,Unsatisfied
11,12,1,35.0,19.0,99.0,1,Satisfied
12,13,1,58.0,20.0,15.0,1,Unsatisfied
13,14,1,24.0,20.0,77.0,1,Satisfied
14,15,0,37.0,20.0,13.0,1,Unsatisfied
15,16,0,22.0,20.0,79.0,1,Satisfied
16,17,1,35.0,21.0,35.0,1,Unsatisfied
17,18,0,20.0,21.0,66.0,1,Unsatisfied
18,19,0,52.0,23.0,29.0,1,Unsatisfied
19,20,1,35.0,23.0,98.0,1,Satisfied

In [51]:
data_frame.to_csv(r'/content/drive/MyDrive/Prepared_Mall_Customers.csv', index=False)